import { EVENT_TYPES } from "./events";

export const DAILY_GOAL_TARGET = 10;

export const ACTIVITY_EVENT_TYPES = [
    EVENT_TYPES.LESSON_COMPLETED,
    EVENT_TYPES.QUIZ_COMPLETED,
    EVENT_TYPES.EXERCISE_COMPLETED,
    EVENT_TYPES.FLASHCARD_REVIEWED
];
