export const EVENT_TYPES = {

    WORD_VIEWED: "WORD_VIEWED",

    VOCABULARY_ADDED: "VOCABULARY_ADDED",

    QUIZ_COMPLETED: "QUIZ_COMPLETED",

    LESSON_COMPLETED: "LESSON_COMPLETED",

    FLASHCARD_REVIEWED: "FLASHCARD_REVIEWED",

    EXERCISE_COMPLETED: "EXERCISE_COMPLETED",

    VIDEO_STARTED: "VIDEO_STARTED",

    VIDEO_RESUMED: "VIDEO_RESUMED",

    VIDEO_COMPLETED: "VIDEO_COMPLETED"

};
